---
apiVersion: v1
kind: Service
metadata:
  name: es-service
  labels:
    app: es-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: http
  selector:
    app: es-logging