apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kib-manual
  name: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kib-manual
  template:
    metadata:
      labels:
        app: kib-manual
    spec:
      containers:
      - image: kibana:7.8.0
        name: kibana
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     port: http
        #     path: /status
        #   initialDelaySeconds: 40
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /status
        #     port: http
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
