apiVersion: v1
kind: Service
metadata:
  labels:
    app: kib-manual
  name: kibana-service
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kib-manual
  type: NodePort
