---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: log-manual
  template:
    metadata:
      labels:
        name: log-manual
    spec:
      hostname: log-manual
      containers:
      - name: logstash
        ports:
        - containerPort: 5044
          name: filebeat
        image: logstash:7.8.0
        volumeMounts:
        - name: log-manual-pipeline
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
      volumes:
      - name: log-manual-pipeline
        configMap:
          name: log-manual-pipeline
          items:
            - key: logstash.conf
              path: logstash.conf